<script src="<?= $wwwUrl ?>/js/order.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous">
    
</script>

<h1>Commandes</h1>

<center><fieldset>Commande de produits
<legend>Commande de produits</legend>
<select class ="order" name="order">
    <?php  foreach ($products as $product) : ?>
    <option value ="<?php echo $product['id']; ?>"><?php echo htmlspecialchars ($product['title']); ?></option>
    <?php endforeach ?>
</select>
</fieldset></center>

<div id ="details">
    <p id="name"></p>
    <p id="description"></p>
    <p id="price"></p>
     <img id="photo" src="" alt="produit">
</div>