<script src="<?= $wwwUrl ?>/js/order.js"></script>
<script src="<?= $wwwUrl ?>/js/basket.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous">
    
</script>

<h1>Commandes</h1>

<center><fieldset>Commande de produits
<legend>Commande de produits</legend>
<select class='order' name="order">
    <?php  foreach ($products as $product) : ?>
    <option value ="<?php echo $product['id']; ?>"><?php echo htmlspecialchars ($product['title']); ?></option>
    <?php endforeach ?>
</select>
</fieldset></center>

<div id ="details">
    <p id="name"></p>
    <p id="description"></p>
    <p><span id="price"></span>€</p>
     <img id="photo" src="" alt="produit">
</div>
<center>
<label for="quantity">Quantité</label>
<input type="number"id="quantity" name="quantity"/>
<button type="button" id="add">Ajouter</button>
</center>
<section>
    <h2>Récupilatif commande</h2>
    <table>
    <thead>
        <tr>
            <th class="number">Quantité</th>
            <th>Produit</th>
            <th class="number">Prix Unitaire</th>
            <th class="number">Prix Total</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    </tbody>   
</section>