<?php if(isset($message)) echo $message; ?>
<center>
<form method="POST" action="" enctype="multipart/form-data">
    <label for="name"> Nom </label>
    <input type="text" name="name" id="name">
    
    <label for="description"> Description </label>
    <textarea name="description" id="description"> </textarea> 
    
    <label for="price"> Prix </label>
    <input type="text" name="price" id="price">
    
    <label for="photo"> Photo </label>
    <input type="file" name="photo" id="photo">
    
    <button> Ajouter un produit </button>
</form>
</center>