<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title> Restaurant</title>
    

    <!-- Feuilles de styles de l'application -->
  
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">

    <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>

    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
</head>
<body>

<!-- En-tête commune -->
<header>
    <h1>
        <a href="<?= $requestUrl ?>">
        <img src="<?= $wwwUrl ?>/images/logo.png" height="63" width="57" alt="3WA Restaurant">Self Germany
        </a>
    </h1>
</header>

<!-- Interface utilisateur -->
<nav class="user-interface">
    <ul class="link-list">
              
            <?php if ( isset($_SESSION['connected_user']) == false ): ?>
                
                <a href="<?= $requestUrl ?>/form">
                    Inscription
                </a>
                <a href="<?= $requestUrl ?>/session">
                    connexion
                </a>
            <?php else: ?>
                <p> Bonjour 
                    <?= htmlspecialchars($_SESSION['connected_user']['firstname']) ?> 
                    <?= htmlspecialchars($_SESSION['connected_user']['lastname']) ?> 
                </p>
                <a href="<?= $requestUrl ?>/disconnect">
                    deconnexion
                </a>
                <a href="<?= $requestUrl ?>/order">
                    Commander
                </a>
            <?php endif; ?>
                                            <!-- Code HTML/PHP à écrire -->
    </ul>
</nav>

<main>
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template'] ?>
</main>

<!-- Pied de page commun -->
<footer>
    <ul class="link-list">
        <li><img src="<?= $wwwUrl ?>/images/payment/visa.png" height="70" width="60" alt="Visa"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/mastercard.png" height="70" width="60" alt="MasterCard"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/paypal.png" height="63" width="60" alt="Paypal"></li>
    </ul>
    <small>Réalisé avec <i class="fa fa-heart"></i>&nbsp; par les élèves de la 3W Academy</small>
</footer>

<!-- Code principal JavaScript de l'application -->
<script src="<?= $wwwUrl ?>/js/main.js"></script>


</body>
</html>